CREATE TABLE Person(
	person_id SERIAL PRIMARY KEY,
	name VARCHAR(100) UNIQUE NOT NULL,
	age INTEGER NOT NULL,
	phone VARCHAR(20) NOT NULL,
	height DECIMAL(3, 2) NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	cpf VARCHAR(11) UNIQUE NOT NULL,
	birthday DATE UNIQUE NOT NULL,
	id_address INTEGER  NOT NULL,
	FOREIGN KEY (id_address) REFERENCES Address(address_id)
)